export const climateData = {
  "Delhi": {
    1: { temp: 14, humidity: 60, weather: "fog" },
    2: { temp: 17, humidity: 55, weather: "clear" },
    3: { temp: 23, humidity: 40, weather: "clear" },
    4: { temp: 30, humidity: 30, weather: "clear" },
    5: { temp: 35, humidity: 25, weather: "hot" },
    6: { temp: 37, humidity: 40, weather: "humid" },
    7: { temp: 34, humidity: 70, weather: "rain" },
    8: { temp: 33, humidity: 75, weather: "rain" },
    9: { temp: 32, humidity: 65, weather: "humid" },
    10: { temp: 28, humidity: 50, weather: "clear" },
    11: { temp: 22, humidity: 50, weather: "clear" },
    12: { temp: 16, humidity: 55, weather: "fog" }
  },
  "Mumbai": {
    1: { temp: 25, humidity: 60, weather: "clear" },
    2: { temp: 26, humidity: 55, weather: "clear" },
    3: { temp: 28, humidity: 60, weather: "clear" },
    4: { temp: 30, humidity: 70, weather: "humid" },
    5: { temp: 32, humidity: 75, weather: "humid" },
    6: { temp: 30, humidity: 85, weather: "rain" },
    7: { temp: 28, humidity: 90, weather: "rain" },
    8: { temp: 28, humidity: 90, weather: "rain" },
    9: { temp: 29, humidity: 85, weather: "rain" },
    10: { temp: 30, humidity: 70, weather: "humid" },
    11: { temp: 28, humidity: 65, weather: "clear" },
    12: { temp: 26, humidity: 60, weather: "clear" }
  },
  "Bangalore": {
    1: { temp: 22, humidity: 50, weather: "clear" },
    2: { temp: 24, humidity: 45, weather: "clear" },
    3: { temp: 27, humidity: 45, weather: "clear" },
    4: { temp: 30, humidity: 55, weather: "clear" },
    5: { temp: 31, humidity: 60, weather: "cloudy" },
    6: { temp: 28, humidity: 70, weather: "rain" },
    7: { temp: 26, humidity: 75, weather: "rain" },
    8: { temp: 26, humidity: 70, weather: "rain" },
    9: { temp: 27, humidity: 65, weather: "cloudy" },
    10: { temp: 26, humidity: 55, weather: "clear" },
    11: { temp: 24, humidity: 50, weather: "clear" },
    12: { temp: 22, humidity: 50, weather: "clear" }
  },
  "Chennai": {
    1: { temp: 25, humidity: 70, weather: "clear" },
    2: { temp: 27, humidity: 65, weather: "clear" },
    3: { temp: 30, humidity: 65, weather: "clear" },
    4: { temp: 33, humidity: 70, weather: "hot" },
    5: { temp: 36, humidity: 75, weather: "hot" },
    6: { temp: 35, humidity: 80, weather: "humid" },
    7: { temp: 34, humidity: 80, weather: "rain" },
    8: { temp: 34, humidity: 80, weather: "rain" },
    9: { temp: 33, humidity: 75, weather: "humid" },
    10: { temp: 31, humidity: 70, weather: "cloudy" },
    11: { temp: 28, humidity: 75, weather: "rain" },
    12: { temp: 26, humidity: 75, weather: "rain" }
  },
  "Kolkata": {
    1: { temp: 18, humidity: 65, weather: "fog" },
    2: { temp: 22, humidity: 60, weather: "clear" },
    3: { temp: 27, humidity: 55, weather: "clear" },
    4: { temp: 31, humidity: 60, weather: "humid" },
    5: { temp: 34, humidity: 70, weather: "humid" },
    6: { temp: 33, humidity: 80, weather: "rain" },
    7: { temp: 31, humidity: 85, weather: "rain" },
    8: { temp: 31, humidity: 85, weather: "rain" },
    9: { temp: 30, humidity: 80, weather: "humid" },
    10: { temp: 28, humidity: 75, weather: "cloudy" },
    11: { temp: 24, humidity: 65, weather: "clear" },
    12: { temp: 20, humidity: 60, weather: "fog" }
  },
  "Hyderabad": {
    1: { temp: 22, humidity: 50, weather: "clear" },
    2: { temp: 25, humidity: 45, weather: "clear" },
    3: { temp: 30, humidity: 40, weather: "clear" },
    4: { temp: 35, humidity: 35, weather: "hot" },
    5: { temp: 38, humidity: 45, weather: "hot" },
    6: { temp: 34, humidity: 65, weather: "rain" },
    7: { temp: 30, humidity: 75, weather: "rain" },
    8: { temp: 29, humidity: 75, weather: "rain" },
    9: { temp: 30, humidity: 70, weather: "cloudy" },
    10: { temp: 28, humidity: 55, weather: "clear" },
    11: { temp: 25, humidity: 50, weather: "clear" },
    12: { temp: 22, humidity: 55, weather: "clear" }
  },
  "Pune": {
    1: { temp: 21, humidity: 40, weather: "clear" },
    2: { temp: 24, humidity: 35, weather: "clear" },
    3: { temp: 28, humidity: 35, weather: "clear" },
    4: { temp: 32, humidity: 40, weather: "clear" },
    5: { temp: 35, humidity: 50, weather: "hot" },
    6: { temp: 30, humidity: 70, weather: "rain" },
    7: { temp: 27, humidity: 80, weather: "rain" },
    8: { temp: 26, humidity: 80, weather: "rain" },
    9: { temp: 27, humidity: 75, weather: "cloudy" },
    10: { temp: 28, humidity: 60, weather: "clear" },
    11: { temp: 24, humidity: 50, weather: "clear" },
    12: { temp: 22, humidity: 45, weather: "clear" }
  },
  "Jaipur": {
    1: { temp: 15, humidity: 45, weather: "fog" },
    2: { temp: 18, humidity: 40, weather: "clear" },
    3: { temp: 25, humidity: 35, weather: "clear" },
    4: { temp: 32, humidity: 30, weather: "clear" },
    5: { temp: 38, humidity: 25, weather: "hot" },
    6: { temp: 39, humidity: 40, weather: "hot" },
    7: { temp: 35, humidity: 55, weather: "rain" },
    8: { temp: 34, humidity: 60, weather: "rain" },
    9: { temp: 33, humidity: 55, weather: "cloudy" },
    10: { temp: 30, humidity: 40, weather: "clear" },
    11: { temp: 24, humidity: 45, weather: "clear" },
    12: { temp: 18, humidity: 50, weather: "fog" }
  },
  "Ahmedabad": {
    1: { temp: 20, humidity: 45, weather: "clear" },
    2: { temp: 24, humidity: 40, weather: "clear" },
    3: { temp: 30, humidity: 35, weather: "clear" },
    4: { temp: 36, humidity: 30, weather: "hot" },
    5: { temp: 40, humidity: 35, weather: "hot" },
    6: { temp: 38, humidity: 50, weather: "humid" },
    7: { temp: 34, humidity: 70, weather: "rain" },
    8: { temp: 33, humidity: 75, weather: "rain" },
    9: { temp: 33, humidity: 65, weather: "humid" },
    10: { temp: 32, humidity: 55, weather: "cloudy" },
    11: { temp: 28, humidity: 50, weather: "clear" },
    12: { temp: 23, humidity: 50, weather: "clear" }
  },
  "Lucknow": {
    1: { temp: 13, humidity: 55, weather: "fog" },
    2: { temp: 16, humidity: 50, weather: "clear" },
    3: { temp: 24, humidity: 45, weather: "clear" },
    4: { temp: 30, humidity: 40, weather: "clear" },
    5: { temp: 35, humidity: 45, weather: "hot" },
    6: { temp: 34, humidity: 60, weather: "rain" },
    7: { temp: 31, humidity: 75, weather: "rain" },
    8: { temp: 30, humidity: 80, weather: "rain" },
    9: { temp: 29, humidity: 75, weather: "humid" },
    10: { temp: 27, humidity: 55, weather: "clear" },
    11: { temp: 22, humidity: 50, weather: "clear" },
    12: { temp: 16, humidity: 55, weather: "fog" }
  },
  "Kolkata": {
    1: { temp: 18, humidity: 60, weather: "clear" },
    2: { temp: 22, humidity: 55, weather: "clear" },
    3: { temp: 28, humidity: 60, weather: "humid" },
    4: { temp: 32, humidity: 65, weather: "hot" },
    5: { temp: 35, humidity: 70, weather: "humid" },
    6: { temp: 33, humidity: 80, weather: "rain" },
    7: { temp: 31, humidity: 85, weather: "rain" },
    8: { temp: 30, humidity: 85, weather: "rain" },
    9: { temp: 30, humidity: 80, weather: "cloudy" },
    10: { temp: 29, humidity: 70, weather: "clear" },
    11: { temp: 25, humidity: 65, weather: "clear" },
    12: { temp: 20, humidity: 60, weather: "fog" }
  },
  "Chandigarh": {
    1: { temp: 12, humidity: 55, weather: "fog" },
    2: { temp: 16, humidity: 50, weather: "clear" },
    3: { temp: 22, humidity: 45, weather: "clear" },
    4: { temp: 30, humidity: 40, weather: "clear" },
    5: { temp: 36, humidity: 45, weather: "hot" },
    6: { temp: 35, humidity: 60, weather: "rain" },
    7: { temp: 32, humidity: 75, weather: "rain" },
    8: { temp: 30, humidity: 75, weather: "rain" },
    9: { temp: 30, humidity: 70, weather: "cloudy" },
    10: { temp: 28, humidity: 60, weather: "clear" },
    11: { temp: 22, humidity: 55, weather: "clear" },
    12: { temp: 16, humidity: 50, weather: "fog" }
  },
  "Bhopal": {
    1: { temp: 18, humidity: 50, weather: "clear" },
    2: { temp: 22, humidity: 45, weather: "clear" },
    3: { temp: 28, humidity: 45, weather: "clear" },
    4: { temp: 34, humidity: 40, weather: "hot" },
    5: { temp: 37, humidity: 50, weather: "hot" },
    6: { temp: 34, humidity: 70, weather: "rain" },
    7: { temp: 30, humidity: 80, weather: "rain" },
    8: { temp: 29, humidity: 80, weather: "rain" },
    9: { temp: 29, humidity: 75, weather: "humid" },
    10: { temp: 28, humidity: 65, weather: "cloudy" },
    11: { temp: 24, humidity: 60, weather: "clear" },
    12: { temp: 20, humidity: 55, weather: "clear" }
  },
  "Dehradun": {
    1: { temp: 10, humidity: 60, weather: "fog" },
    2: { temp: 14, humidity: 55, weather: "clear" },
    3: { temp: 20, humidity: 50, weather: "clear" },
    4: { temp: 26, humidity: 45, weather: "clear" },
    5: { temp: 30, humidity: 55, weather: "warm" },
    6: { temp: 28, humidity: 70, weather: "rain" },
    7: { temp: 26, humidity: 80, weather: "rain" },
    8: { temp: 25, humidity: 85, weather: "rain" },
    9: { temp: 26, humidity: 75, weather: "cloudy" },
    10: { temp: 24, humidity: 65, weather: "clear" },
    11: { temp: 18, humidity: 55, weather: "clear" },
    12: { temp: 12, humidity: 60, weather: "fog" }
  },
  "Srinagar": {
    1: { temp: 2, humidity: 60, weather: "snow" },
    2: { temp: 5, humidity: 55, weather: "snow" },
    3: { temp: 10, humidity: 50, weather: "cloudy" },
    4: { temp: 15, humidity: 50, weather: "clear" },
    5: { temp: 20, humidity: 45, weather: "clear" },
    6: { temp: 25, humidity: 50, weather: "clear" },
    7: { temp: 27, humidity: 55, weather: "clear" },
    8: { temp: 26, humidity: 60, weather: "cloudy" },
    9: { temp: 22, humidity: 55, weather: "clear" },
    10: { temp: 16, humidity: 50, weather: "cloudy" },
    11: { temp: 10, humidity: 60, weather: "snow" },
    12: { temp: 5, humidity: 65, weather: "snow" }
  },
  "Ooty": {
    1: { temp: 12, humidity: 60, weather: "clear" },
    2: { temp: 14, humidity: 55, weather: "clear" },
    3: { temp: 17, humidity: 60, weather: "clear" },
    4: { temp: 19, humidity: 65, weather: "clear" },
    5: { temp: 20, humidity: 70, weather: "cloudy" },
    6: { temp: 18, humidity: 85, weather: "rain" },
    7: { temp: 17, humidity: 90, weather: "rain" },
    8: { temp: 18, humidity: 85, weather: "rain" },
    9: { temp: 19, humidity: 80, weather: "rain" },
    10: { temp: 18, humidity: 70, weather: "cloudy" },
    11: { temp: 16, humidity: 65, weather: "clear" },
    12: { temp: 14, humidity: 60, weather: "clear" }
  },
  "Darjeeling": {
    1: { temp: 5, humidity: 70, weather: "cold" },
    2: { temp: 7, humidity: 65, weather: "clear" },
    3: { temp: 12, humidity: 60, weather: "clear" },
    4: { temp: 15, humidity: 65, weather: "cloudy" },
    5: { temp: 18, humidity: 75, weather: "cloudy" },
    6: { temp: 20, humidity: 90, weather: "rain" },
    7: { temp: 19, humidity: 92, weather: "rain" },
    8: { temp: 19, humidity: 90, weather: "rain" },
    9: { temp: 18, humidity: 85, weather: "rain" },
    10: { temp: 16, humidity: 75, weather: "cloudy" },
    11: { temp: 12, humidity: 70, weather: "clear" },
    12: { temp: 7, humidity: 65, weather: "cold" }
  },
  "Kochi": {
    1: { temp: 28, humidity: 75, weather: "clear" },
    2: { temp: 30, humidity: 75, weather: "clear" },
    3: { temp: 32, humidity: 80, weather: "cloudy" },
    4: { temp: 34, humidity: 85, weather: "cloudy" },
    5: { temp: 32, humidity: 90, weather: "rain" },
    6: { temp: 30, humidity: 92, weather: "rain" },
    7: { temp: 28, humidity: 95, weather: "rain" },
    8: { temp: 28, humidity: 95, weather: "rain" },
    9: { temp: 29, humidity: 90, weather: "rain" },
    10: { temp: 30, humidity: 85, weather: "cloudy" },
    11: { temp: 29, humidity: 80, weather: "cloudy" },
    12: { temp: 28, humidity: 75, weather: "clear" }
  },
  "Rishikesh": {
    1: { temp: 13, humidity: 55, weather: "clear" },
    2: { temp: 16, humidity: 50, weather: "clear" },
    3: { temp: 22, humidity: 45, weather: "clear" },
    4: { temp: 30, humidity: 50, weather: "clear" },
    5: { temp: 34, humidity: 60, weather: "cloudy" },
    6: { temp: 32, humidity: 75, weather: "rain" },
    7: { temp: 30, humidity: 85, weather: "rain" },
    8: { temp: 29, humidity: 85, weather: "rain" },
    9: { temp: 28, humidity: 70, weather: "rain" },
    10: { temp: 25, humidity: 60, weather: "cloudy" },
    11: { temp: 20, humidity: 50, weather: "clear" },
    12: { temp: 15, humidity: 55, weather: "clear" }
  },

  "Auli": {
    1: { temp: -2, humidity: 60, weather: "snow" },
    2: { temp: 0, humidity: 55, weather: "snow" },
    3: { temp: 5, humidity: 50, weather: "clear" },
    4: { temp: 10, humidity: 55, weather: "clear" },
    5: { temp: 15, humidity: 60, weather: "cloudy" },
    6: { temp: 17, humidity: 80, weather: "rain" },
    7: { temp: 18, humidity: 85, weather: "rain" },
    8: { temp: 18, humidity: 80, weather: "rain" },
    9: { temp: 16, humidity: 75, weather: "cloudy" },
    10: { temp: 14, humidity: 60, weather: "clear" },
    11: { temp: 8, humidity: 55, weather: "clear" },
    12: { temp: 2, humidity: 60, weather: "snow" }
  },

  "Jaisalmer": {
    1: { temp: 16, humidity: 30, weather: "clear" },
    2: { temp: 20, humidity: 25, weather: "clear" },
    3: { temp: 28, humidity: 20, weather: "clear" },
    4: { temp: 35, humidity: 15, weather: "clear" },
    5: { temp: 40, humidity: 20, weather: "clear" },
    6: { temp: 42, humidity: 30, weather: "clear" },
    7: { temp: 39, humidity: 40, weather: "cloudy" },
    8: { temp: 37, humidity: 50, weather: "rain" },
    9: { temp: 35, humidity: 45, weather: "cloudy" },
    10: { temp: 30, humidity: 35, weather: "clear" },
    11: { temp: 24, humidity: 30, weather: "clear" },
    12: { temp: 18, humidity: 25, weather: "clear" }
  },

  "Tawang": {
    1: { temp: -5, humidity: 55, weather: "snow" },
    2: { temp: -2, humidity: 50, weather: "snow" },
    3: { temp: 3, humidity: 55, weather: "cloudy" },
    4: { temp: 8, humidity: 60, weather: "clear" },
    5: { temp: 12, humidity: 65, weather: "cloudy" },
    6: { temp: 15, humidity: 85, weather: "rain" },
    7: { temp: 16, humidity: 90, weather: "rain" },
    8: { temp: 16, humidity: 90, weather: "rain" },
    9: { temp: 15, humidity: 85, weather: "cloudy" },
    10: { temp: 12, humidity: 70, weather: "cloudy" },
    11: { temp: 7, humidity: 60, weather: "clear" },
    12: { temp: 0, humidity: 55, weather: "snow" }
  }
};
